version: '3'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    networks:
      - app-net
  app:
    build:
      context: ./app
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
